/* Auto-generated by genmsg_cpp for file /home/dev/cs7630_robotics/raptor/msg/rel_pos_req.msg */
#ifndef RAPTOR_MESSAGE_REL_POS_REQ_H
#define RAPTOR_MESSAGE_REL_POS_REQ_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace raptor
{
template <class ContainerAllocator>
struct rel_pos_req_ {
  typedef rel_pos_req_<ContainerAllocator> Type;

  rel_pos_req_()
  : theta_rad(0.0)
  , val(0.0)
  , time_sec(0.0)
  {
  }

  rel_pos_req_(const ContainerAllocator& _alloc)
  : theta_rad(0.0)
  , val(0.0)
  , time_sec(0.0)
  {
  }

  typedef float _theta_rad_type;
  float theta_rad;

  typedef float _val_type;
  float val;

  typedef float _time_sec_type;
  float time_sec;


private:
  static const char* __s_getDataType_() { return "raptor/rel_pos_req"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "8a051cbaa402dd0d06d01a30168d23d8"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "float32 theta_rad\n\
float32 val\n\
float32 time_sec\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, theta_rad);
    ros::serialization::serialize(stream, val);
    ros::serialization::serialize(stream, time_sec);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, theta_rad);
    ros::serialization::deserialize(stream, val);
    ros::serialization::deserialize(stream, time_sec);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(theta_rad);
    size += ros::serialization::serializationLength(val);
    size += ros::serialization::serializationLength(time_sec);
    return size;
  }

  typedef boost::shared_ptr< ::raptor::rel_pos_req_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::raptor::rel_pos_req_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct rel_pos_req
typedef  ::raptor::rel_pos_req_<std::allocator<void> > rel_pos_req;

typedef boost::shared_ptr< ::raptor::rel_pos_req> rel_pos_reqPtr;
typedef boost::shared_ptr< ::raptor::rel_pos_req const> rel_pos_reqConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::raptor::rel_pos_req_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::raptor::rel_pos_req_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace raptor

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::raptor::rel_pos_req_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::raptor::rel_pos_req_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::raptor::rel_pos_req_<ContainerAllocator> > {
  static const char* value() 
  {
    return "8a051cbaa402dd0d06d01a30168d23d8";
  }

  static const char* value(const  ::raptor::rel_pos_req_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x8a051cbaa402dd0dULL;
  static const uint64_t static_value2 = 0x06d01a30168d23d8ULL;
};

template<class ContainerAllocator>
struct DataType< ::raptor::rel_pos_req_<ContainerAllocator> > {
  static const char* value() 
  {
    return "raptor/rel_pos_req";
  }

  static const char* value(const  ::raptor::rel_pos_req_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::raptor::rel_pos_req_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32 theta_rad\n\
float32 val\n\
float32 time_sec\n\
";
  }

  static const char* value(const  ::raptor::rel_pos_req_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::raptor::rel_pos_req_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::raptor::rel_pos_req_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.theta_rad);
    stream.next(m.val);
    stream.next(m.time_sec);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct rel_pos_req_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::raptor::rel_pos_req_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::raptor::rel_pos_req_<ContainerAllocator> & v) 
  {
    s << indent << "theta_rad: ";
    Printer<float>::stream(s, indent + "  ", v.theta_rad);
    s << indent << "val: ";
    Printer<float>::stream(s, indent + "  ", v.val);
    s << indent << "time_sec: ";
    Printer<float>::stream(s, indent + "  ", v.time_sec);
  }
};


} // namespace message_operations
} // namespace ros

#endif // RAPTOR_MESSAGE_REL_POS_REQ_H

