(cl:defpackage raptor_commander-srv
  (:use )
  (:export
   "GETADVICEPD"
   "<GETADVICEPD-REQUEST>"
   "GETADVICEPD-REQUEST"
   "<GETADVICEPD-RESPONSE>"
   "GETADVICEPD-RESPONSE"
   "GETADVICEFD"
   "<GETADVICEFD-REQUEST>"
   "GETADVICEFD-REQUEST"
   "<GETADVICEFD-RESPONSE>"
   "GETADVICEFD-RESPONSE"
  ))

