(cl:defpackage raptor_commander-srv
  (:use )
  (:export
   "GETADVICEFLEE"
   "<GETADVICEFLEE-REQUEST>"
   "GETADVICEFLEE-REQUEST"
   "<GETADVICEFLEE-RESPONSE>"
   "GETADVICEFLEE-RESPONSE"
   "GETADVICEDET"
   "<GETADVICEDET-REQUEST>"
   "GETADVICEDET-REQUEST"
   "<GETADVICEDET-RESPONSE>"
   "GETADVICEDET-RESPONSE"
   "GETADVICEFD"
   "<GETADVICEFD-REQUEST>"
   "GETADVICEFD-REQUEST"
   "<GETADVICEFD-RESPONSE>"
   "GETADVICEFD-RESPONSE"
  ))

