(cl:defpackage rovio_shared-srv
  (:use )
  (:export
   "ROVIO_POSITION"
   "<ROVIO_POSITION-REQUEST>"
   "ROVIO_POSITION-REQUEST"
   "<ROVIO_POSITION-RESPONSE>"
   "ROVIO_POSITION-RESPONSE"
   "WAV_PLAY"
   "<WAV_PLAY-REQUEST>"
   "WAV_PLAY-REQUEST"
   "<WAV_PLAY-RESPONSE>"
   "WAV_PLAY-RESPONSE"
   "HEAD_CTRL"
   "<HEAD_CTRL-REQUEST>"
   "HEAD_CTRL-REQUEST"
   "<HEAD_CTRL-RESPONSE>"
   "HEAD_CTRL-RESPONSE"
   "TWIST_SRV"
   "<TWIST_SRV-REQUEST>"
   "TWIST_SRV-REQUEST"
   "<TWIST_SRV-RESPONSE>"
   "TWIST_SRV-RESPONSE"
  ))

