/* Auto-generated by genmsg_cpp for file /home/dev/cs7630_robotics/raptor/srv/position_request_srv.srv */
#ifndef RAPTOR_SERVICE_POSITION_REQUEST_SRV_H
#define RAPTOR_SERVICE_POSITION_REQUEST_SRV_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace raptor
{
template <class ContainerAllocator>
struct position_request_srvRequest_ {
  typedef position_request_srvRequest_<ContainerAllocator> Type;

  position_request_srvRequest_()
  : x(0)
  , y(0)
  , val(0.0)
  , time_sec(0.0)
  {
  }

  position_request_srvRequest_(const ContainerAllocator& _alloc)
  : x(0)
  , y(0)
  , val(0.0)
  , time_sec(0.0)
  {
  }

  typedef int16_t _x_type;
  int16_t x;

  typedef int16_t _y_type;
  int16_t y;

  typedef float _val_type;
  float val;

  typedef float _time_sec_type;
  float time_sec;


private:
  static const char* __s_getDataType_() { return "raptor/position_request_srvRequest"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "2a22c4eddd9fc3ec356ab2303dd85ac7"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "2a22c4eddd9fc3ec356ab2303dd85ac7"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "int16 x\n\
int16 y\n\
float32 val\n\
float32 time_sec\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, x);
    ros::serialization::serialize(stream, y);
    ros::serialization::serialize(stream, val);
    ros::serialization::serialize(stream, time_sec);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, x);
    ros::serialization::deserialize(stream, y);
    ros::serialization::deserialize(stream, val);
    ros::serialization::deserialize(stream, time_sec);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(x);
    size += ros::serialization::serializationLength(y);
    size += ros::serialization::serializationLength(val);
    size += ros::serialization::serializationLength(time_sec);
    return size;
  }

  typedef boost::shared_ptr< ::raptor::position_request_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::raptor::position_request_srvRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct position_request_srvRequest
typedef  ::raptor::position_request_srvRequest_<std::allocator<void> > position_request_srvRequest;

typedef boost::shared_ptr< ::raptor::position_request_srvRequest> position_request_srvRequestPtr;
typedef boost::shared_ptr< ::raptor::position_request_srvRequest const> position_request_srvRequestConstPtr;


template <class ContainerAllocator>
struct position_request_srvResponse_ {
  typedef position_request_srvResponse_<ContainerAllocator> Type;

  position_request_srvResponse_()
  {
  }

  position_request_srvResponse_(const ContainerAllocator& _alloc)
  {
  }


private:
  static const char* __s_getDataType_() { return "raptor/position_request_srvResponse"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "d41d8cd98f00b204e9800998ecf8427e"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "2a22c4eddd9fc3ec356ab2303dd85ac7"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    return size;
  }

  typedef boost::shared_ptr< ::raptor::position_request_srvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::raptor::position_request_srvResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct position_request_srvResponse
typedef  ::raptor::position_request_srvResponse_<std::allocator<void> > position_request_srvResponse;

typedef boost::shared_ptr< ::raptor::position_request_srvResponse> position_request_srvResponsePtr;
typedef boost::shared_ptr< ::raptor::position_request_srvResponse const> position_request_srvResponseConstPtr;

struct position_request_srv
{

typedef position_request_srvRequest Request;
typedef position_request_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct position_request_srv
} // namespace raptor

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::raptor::position_request_srvRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::raptor::position_request_srvRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::raptor::position_request_srvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "2a22c4eddd9fc3ec356ab2303dd85ac7";
  }

  static const char* value(const  ::raptor::position_request_srvRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x2a22c4eddd9fc3ecULL;
  static const uint64_t static_value2 = 0x356ab2303dd85ac7ULL;
};

template<class ContainerAllocator>
struct DataType< ::raptor::position_request_srvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "raptor/position_request_srvRequest";
  }

  static const char* value(const  ::raptor::position_request_srvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::raptor::position_request_srvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int16 x\n\
int16 y\n\
float32 val\n\
float32 time_sec\n\
\n\
";
  }

  static const char* value(const  ::raptor::position_request_srvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::raptor::position_request_srvRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::raptor::position_request_srvResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::raptor::position_request_srvResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::raptor::position_request_srvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::raptor::position_request_srvResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::raptor::position_request_srvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "raptor/position_request_srvResponse";
  }

  static const char* value(const  ::raptor::position_request_srvResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::raptor::position_request_srvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
";
  }

  static const char* value(const  ::raptor::position_request_srvResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::raptor::position_request_srvResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::raptor::position_request_srvRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.x);
    stream.next(m.y);
    stream.next(m.val);
    stream.next(m.time_sec);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct position_request_srvRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::raptor::position_request_srvResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct position_request_srvResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<raptor::position_request_srv> {
  static const char* value() 
  {
    return "2a22c4eddd9fc3ec356ab2303dd85ac7";
  }

  static const char* value(const raptor::position_request_srv&) { return value(); } 
};

template<>
struct DataType<raptor::position_request_srv> {
  static const char* value() 
  {
    return "raptor/position_request_srv";
  }

  static const char* value(const raptor::position_request_srv&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<raptor::position_request_srvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "2a22c4eddd9fc3ec356ab2303dd85ac7";
  }

  static const char* value(const raptor::position_request_srvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<raptor::position_request_srvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "raptor/position_request_srv";
  }

  static const char* value(const raptor::position_request_srvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<raptor::position_request_srvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "2a22c4eddd9fc3ec356ab2303dd85ac7";
  }

  static const char* value(const raptor::position_request_srvResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<raptor::position_request_srvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "raptor/position_request_srv";
  }

  static const char* value(const raptor::position_request_srvResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // RAPTOR_SERVICE_POSITION_REQUEST_SRV_H

