/* Auto-generated by genmsg_cpp for file /home/dev/cs7630_robotics/raptor/srv/state_set_srv.srv */
#ifndef RAPTOR_SERVICE_STATE_SET_SRV_H
#define RAPTOR_SERVICE_STATE_SET_SRV_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace raptor
{
template <class ContainerAllocator>
struct state_set_srvRequest_ {
  typedef state_set_srvRequest_<ContainerAllocator> Type;

  state_set_srvRequest_()
  : model(0)
  , state(0)
  {
  }

  state_set_srvRequest_(const ContainerAllocator& _alloc)
  : model(0)
  , state(0)
  {
  }

  typedef int16_t _model_type;
  int16_t model;

  typedef int16_t _state_type;
  int16_t state;


private:
  static const char* __s_getDataType_() { return "raptor/state_set_srvRequest"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "75c5b792941ec6b4ff04cb01b9bf3ec3"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "75c5b792941ec6b4ff04cb01b9bf3ec3"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "int16 model\n\
int16 state\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, model);
    ros::serialization::serialize(stream, state);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, model);
    ros::serialization::deserialize(stream, state);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(model);
    size += ros::serialization::serializationLength(state);
    return size;
  }

  typedef boost::shared_ptr< ::raptor::state_set_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::raptor::state_set_srvRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct state_set_srvRequest
typedef  ::raptor::state_set_srvRequest_<std::allocator<void> > state_set_srvRequest;

typedef boost::shared_ptr< ::raptor::state_set_srvRequest> state_set_srvRequestPtr;
typedef boost::shared_ptr< ::raptor::state_set_srvRequest const> state_set_srvRequestConstPtr;


template <class ContainerAllocator>
struct state_set_srvResponse_ {
  typedef state_set_srvResponse_<ContainerAllocator> Type;

  state_set_srvResponse_()
  {
  }

  state_set_srvResponse_(const ContainerAllocator& _alloc)
  {
  }


private:
  static const char* __s_getDataType_() { return "raptor/state_set_srvResponse"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "d41d8cd98f00b204e9800998ecf8427e"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "75c5b792941ec6b4ff04cb01b9bf3ec3"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    return size;
  }

  typedef boost::shared_ptr< ::raptor::state_set_srvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::raptor::state_set_srvResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct state_set_srvResponse
typedef  ::raptor::state_set_srvResponse_<std::allocator<void> > state_set_srvResponse;

typedef boost::shared_ptr< ::raptor::state_set_srvResponse> state_set_srvResponsePtr;
typedef boost::shared_ptr< ::raptor::state_set_srvResponse const> state_set_srvResponseConstPtr;

struct state_set_srv
{

typedef state_set_srvRequest Request;
typedef state_set_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct state_set_srv
} // namespace raptor

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::raptor::state_set_srvRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::raptor::state_set_srvRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::raptor::state_set_srvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "75c5b792941ec6b4ff04cb01b9bf3ec3";
  }

  static const char* value(const  ::raptor::state_set_srvRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x75c5b792941ec6b4ULL;
  static const uint64_t static_value2 = 0xff04cb01b9bf3ec3ULL;
};

template<class ContainerAllocator>
struct DataType< ::raptor::state_set_srvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "raptor/state_set_srvRequest";
  }

  static const char* value(const  ::raptor::state_set_srvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::raptor::state_set_srvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int16 model\n\
int16 state\n\
\n\
";
  }

  static const char* value(const  ::raptor::state_set_srvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::raptor::state_set_srvRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::raptor::state_set_srvResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::raptor::state_set_srvResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::raptor::state_set_srvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::raptor::state_set_srvResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::raptor::state_set_srvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "raptor/state_set_srvResponse";
  }

  static const char* value(const  ::raptor::state_set_srvResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::raptor::state_set_srvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
";
  }

  static const char* value(const  ::raptor::state_set_srvResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::raptor::state_set_srvResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::raptor::state_set_srvRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.model);
    stream.next(m.state);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct state_set_srvRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::raptor::state_set_srvResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct state_set_srvResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<raptor::state_set_srv> {
  static const char* value() 
  {
    return "75c5b792941ec6b4ff04cb01b9bf3ec3";
  }

  static const char* value(const raptor::state_set_srv&) { return value(); } 
};

template<>
struct DataType<raptor::state_set_srv> {
  static const char* value() 
  {
    return "raptor/state_set_srv";
  }

  static const char* value(const raptor::state_set_srv&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<raptor::state_set_srvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "75c5b792941ec6b4ff04cb01b9bf3ec3";
  }

  static const char* value(const raptor::state_set_srvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<raptor::state_set_srvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "raptor/state_set_srv";
  }

  static const char* value(const raptor::state_set_srvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<raptor::state_set_srvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "75c5b792941ec6b4ff04cb01b9bf3ec3";
  }

  static const char* value(const raptor::state_set_srvResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<raptor::state_set_srvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "raptor/state_set_srv";
  }

  static const char* value(const raptor::state_set_srvResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // RAPTOR_SERVICE_STATE_SET_SRV_H

